<?php

namespace Database\Seeders;

use App\Models\activity;
use Illuminate\Database\Seeder;

class ActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $activities = [
            [
                'name' => 'Membuat Pending Billing Approval Order',
                'start_date' => \Carbon\Carbon::createFromDate(2023,3,16)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,3,16)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'TSQ Ulang / Resubmit Order',
                'start_date' => \Carbon\Carbon::createFromDate(2023,3,17)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,3,17)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Customer Account di UAT',
                'start_date' => \Carbon\Carbon::createFromDate(2023,3,20)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,3,20)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Attribute Product Neucentrix',
                'start_date' => \Carbon\Carbon::createFromDate(2023,3,21)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,3,24)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Query Comment Order Comment Line Item',
                'start_date' => \Carbon\Carbon::createFromDate(2023,3,27)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,3,27)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Export Database ke Excel',
                'start_date' => \Carbon\Carbon::createFromDate(2023,3,28)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,3,28)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Melanjutkan Order Sampai Billing Completed',
                'start_date' => \Carbon\Carbon::createFromDate(2023,3,29)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,3,29)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat resume order',
                'start_date' => \Carbon\Carbon::createFromDate(2023,3,30)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,3,30)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] Transfer Knowledge Pekerjaan Enhancement Product Pricing Tools: Ritel Product Management',
                'start_date' => \Carbon\Carbon::createFromDate(2023,3,31)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,3,31)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Order NeucentrIX Layer 1 Untuk Tes',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,3)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,3)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Disconnect Order NeuCentrIX',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,4)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,4)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Tes Active Order NeuCentrIX',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,5)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,5)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'membuat order disconnect neucentrix sampai bilkom',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,6)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,6)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Cek default value MRC pada produk TIE LINE',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,10)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,10)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Menambahkan MRC pada TIE Line',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,11)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,11)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Export TIE Line ke Production',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,12)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,12)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Uji MRC Ototmatis Product TIE Line (Active Order)',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,13)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,13)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Uji MRC Ototmatis Product TIE Line (Modify Order)',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,13)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,13)->toDateTimeString(),
                'status' => 'Completed',
            ],

            [
                'name' => 'Export Database ke Excel',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,17)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,17)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Query TIE Line Order',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,18)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,18)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Query TIE Line Order',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,18)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,18)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Query Data Prov Start Mulai dari Tanggal 6 April Ke Bawah',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,26)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,26)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Export Data Order Prov Start yang sebelum tanggal 6 april via SQL query',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,27)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,27)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Merapihkan Produk TIE Line',
                'start_date' => \Carbon\Carbon::createFromDate(2023,4,28)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,4,28)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Menambahkan restriction pada product Masking 150AXYZ',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,2)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,2)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting On site] Pembahasan Produk Modelling FAB IT Tools New Product DataComm Test Lanjutan 8IC FAB IT Tools untuk Produk NeuCentrIX Interconnect Layer 1',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,5)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,5)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Tes Product untuk D2P NeuCentrIX Layer 1',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,8)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,8)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] Diskusi Penyiapan Product Modeling Layanan SCC 3.0 enhancement penambahan paketisasi layanan 2 & Development fitur burstable di IT Tools pada Product IP Transit dan turunannya',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,9)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,9)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] Pembahasan Penyesuaian IT Tools Layanan SIP Trunk',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,10)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,10)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Penambahan IP Up To di product SIP Trunk',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,11)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,11)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Menambahkan Product di AStinet ASTINet Single IP SDWAN attribute VPN IP Service type new value : VPN IP Netmonk',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,12)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,12)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Mengubah nama product Cloud PBX to SIP Trunk Plus',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,15)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,15)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Penyesuaian Tarif SIP Trunk',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,16)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,16)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'membuat constrain ke SIP Trunk',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,17)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,17)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] Penyiapan FAB IT Tools penambahan fitur burstable Layanan IP Peering',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,19)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,19)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Menambahkan IP Peering Burstable IP Peering Installation NRC ke IP Transit',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,22)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,22)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Mengubah Attribute Max Value pada product IP Peering Burstable',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,23)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,23)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Bersama ini, kami sampaikan undangan dengan agenda pembahasan mapping ncx, tibs dan trems',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,24)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,24)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Test Mengubah Tarif ASTINet',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,25)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,25)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Menyesuaikan tarif ASTINet Fit dengan nota dinas',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,26)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,26)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Penyesuaian kebijakan tarif layanan di neucentrix',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,29)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,29)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Pra UAT Datacomm Product Q2 2023 ',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,30)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,30)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Diskusi Penyiapan FAB IT Tools layanan SCC 3.0 dan kesiapan UAT',
                'start_date' => \Carbon\Carbon::createFromDate(2023,5,31)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,5,31)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Menambahakan value baru pada attribute Location neuCentrIX Origin New Value : - Jakarta - Meruya New Value : - NeutraDC - Serpong',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,5)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,5)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Location neuCentrIX Destination New Value : - Jakarta - Meruya New Value : - NeutraDC - Serpong Name Attributed : NCIX Latency New Value : Protected',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,6)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,6)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Constraint LOV Location NeuCentrIX Origin Destination - Jakarta - Jatinegara',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,7)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,7)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] UAT flow provisioining end to end SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,7)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,9)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Order Dengan Product DDoS Protection',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,9)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,9)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] Agenda : Show penyesuaian Activity Status Log',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,9)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,9)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] Transfer Knowledge Enhancement C-CAREnt Deliverable II - Functionality C-CAREnt',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,9)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,9)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Order Dengan Product ASTINet Single IP SDWAN & VPN IP Netmonk (2 Orders)',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,12)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,12)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting ] UAT flow provisioining end to end SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,12)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,14)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Activation Order 3 IP Transit WIC Lokasi STO : MDC Sumatera Latlong : 3.5833491233160633 98.66804122924806 Bandwidth : 500 Mbps Request IPv6 : no BW Performance : yes',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,12)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,12)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Mengubah Order SCC Netflix 450mbs ke 700mbps',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,13)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,13)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Diskusi Error yang terjadi pada perubahan order SCC Netflix 700mbps',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,13)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,13)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Koordinasi error pada order AO 2 SCC paket Bundle : Garena, Akamai, Conversant',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,14)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,14)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Mencari data LID, Service ID No Order melalui Query Database',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,14)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,14)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting On site] Diskusi Terkait Update Milestone Sequence via Database Query',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,14)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,14)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Mencari Query Untuk Cek Double Sequence via Database SQL',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,14)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,14)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Mencari Double Sequence via Database Query',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,14)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,14)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Mencari Null Milestone via Database Query',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Melakukan Backup Data Pada Milestone yang Memiliki Nila Null',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Memperbaiki Null Milestone via Database Query',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Menambahkan milestone Fullfil billing complete yang tidak synchron antara root line item & child line item',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting On site] Finalisasi UAT & Review untuk VPN IP Netmonk & ASTINet Single IP SDWAN',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,16)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] Diskusi Requirement Produk Konfig HDC di NCX Bootcamp Perbaikan ISR CA DWS',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] Testing Hasil Perbaikan ISR CA DWS',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat 3 Order Untuk Keperluan Test Product NCX WIB',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,15)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Modification Order 1 MO Upgrade BW untuk test product SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,16)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,16)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Diskusi terkait VPN IP Netmonk Product WIB',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,19)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,19)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Diskusi ASTINET Single IP SDWAN terkait order tes yang error',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,20)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,20)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Persiapan D2P Product ASTINet Single IP SDWAN VPN IP Netmonk',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,21)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,21)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] Diskusi Hasil LAB Trial SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,22)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,22)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] Pembahasan Penyesuaian IT Tools Layanan Port Interconnection',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,23)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,23)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] Pra 8IC FAB IT Tools Astinet Branch SDWAN',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,23)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,23)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat order tes Port Interconnect untuk tes price',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,23)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,23)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] Pembahasan Pengelolaan Order Jasa Jaringan periode tagihan Juli 2023',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,26)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,26)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] 8IC FAB IT Tools Astinet Branch SDWAN',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,26)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,27)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Melakukan config ulang pada product price ASTINET SDWAN',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,27)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,27)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat order untuk test price ASTINET SINGLE IP SDWAN',
                'start_date' => \Carbon\Carbon::createFromDate(2023,6,27)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,6,27)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Order Test IP Transit Peering Burstable',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,3)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,3)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Pembahasan validasi Kebutuhan Development FAB IT Tools Layanan Akses Call Cente',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,4)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,4)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'D2P CNDC NeuCentrix Enhancement Price',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,5)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,5)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Mengconfig Price Adjustment DC Install Rent Rack PrcAdj01',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,5)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,5)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '8IC FAB IT Tools Layanan SMS A2P Domestik',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,5)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,6)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat order untuk test 8IC SMS A2P',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,5)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,5)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat disconnect order test 8IC SMS A2P',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,6)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,6)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat resume order dari suspend order test 8IC SMS A2P',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,6)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,6)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat order Active baru untuk test lanjutan SMS A2P 8IC demi mencapai kesesuaian dengan design awal product',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,7)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,7)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'melakukan pengecekan status order sudah sesuai dengan tujuan atau belum SMS A2P',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,7)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,7)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'melanjutkan pembuatan active order untuk proses test 8iC SMS A2P',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,10)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,10)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Melakukan sync tarif ke TIBs SMS A2P',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,10)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,10)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Melakukan pengecekan order agar sesuai dengan product design SMS A2P',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,10)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,10)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat modify order untuk keperluan test 8IC product SMS A2P',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,11)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,11)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Diskusi Hasil Lab Trial SCC 3.0 Skenario Lanjutan',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,11)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,11)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat order VPN IP',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,12)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,12)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Query Untuk Mendapatkan Data Quote, Quote Item, Order Order Item',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,13)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,13)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Diskusi Redesign FAB IT Tools Layanan Specific Content Connectivity SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,14)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,14)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Order Test IP Trasit Peering Burstable',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,14)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,14)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Memperbaiki Error Pada Product Astinet',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,17)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,17)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Order Test Product SMS A2P Untuk 8IC',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,17)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,17)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Mengcompeletekan order IP Peering Burstable',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,18)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,18)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Modify order IP Peering Burstable',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,18)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,18)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] 8IC Test FAB IT Tools VPN IP Netmonk',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,20)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,21)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '[Meeting Online] Meeting Product Review',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,24)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,24)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Memperbaiki Order Belum Completed karena ada error',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,24)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,24)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Suspend Order 8IC SMS A2P',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,24)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,24)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Mengubah Note attribute Spesific Content Conectivity',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,24)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,24)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat new order test NeuCentrIX Layer 1',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,25)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,25)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Resume Order Test SMS A2P 8IC',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,25)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,25)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Mengubah Note Layanan IP Transit menjadi Apabila customer memiliki Layanan IP Transit yang aktif silahkan pilih "YES"',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,25)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,25)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat active order SCC 3.0  
                           SCC : Paket Netflix, Akamai, AWS Lokasi 
                           STO : MDC Sumatera 
                           Bandwidth : 500 Mbps, Global 50 Mbps',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,26)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,26)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat DO Test SMS A2P Final 8IC',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,26)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,26)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Testing FAB IT Tools devt. untuk skema single order layanan SCC 3.0 AO, MO, SO, RO, DO',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,26)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,28)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Meng complete kan Order NeuCentrIX Layer 1',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,26)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,26)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Resubmit order test SCC',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,27)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,27)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Query untuk mencari order NeuCentrIX lokasi Batam',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,27)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,27)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Pembahasan Enhancement IT Tools Port Interkoneksi Wholesale',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,27)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,27)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat order test SCC kedua IP Transit Beda Bandwidth',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,28)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,28)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Memperbaiki order yang error dan melakukan resubmit pada order test SCC AO1 dan AO2',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,28)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,28)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Buat ulang order AO1 untuk test lanjutan',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,28)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,7,28)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Lanjutan UAT untuk semua skenario layanan SCC 3.0 AO, MO, SO, RO, DO',
                'start_date' => \Carbon\Carbon::createFromDate(2023,7,31)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,2)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Buat order Akses Call Center',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,1)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,1)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat order DDoS Protection',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,2)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,2)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'membuat order MO Modify Order NeuCentrIX Interconnect Layer',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,3)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,3)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'UAT Enhancement CRM Application Fase 2 Deliverable 2',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,4)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,4)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Finalisasi UAT untuk semua skenario layanan SCC 3.0 AO, MO, SO, RO, DO',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,7)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,9)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat order Modify product test DDOS Protection',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,7)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,7)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'membuat order scenario test 2 product SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,7)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,7)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Meng Completed kan AO1 SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,8)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,8)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'membuat MO test skenario SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,8)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,8)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'membuat note pada attribute POP IP Transit WIC',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,8)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,8)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Meng completed kan order scenario 2 SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,8)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,8)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat Order Baru Scenario 3 untuk test SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,9)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,9)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat suspend order scenario AO 1 SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,10)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,10)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'membuat order test created date',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,10)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,10)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat skenario query database',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,10)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,10)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Penyelesaian UAT IT Tools end to end untuk 4 sisa skenario terakhir detail progress dan skenario ada pada poin 3',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,14)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,16)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat order untuk skenario test resume order SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,14)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,14)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat SO test untuk product DDOS Protection',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,16)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,16)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Resubmit order error pada test SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,16)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,16)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'mengubah status order test scenario Resume Order menjadi completed SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,16)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,16)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat order skenario Disconnect Order test SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,16)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,16)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Mencari order test untuk keperluan unit test pasca Dev to Prod',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,16)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,16)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Meng completed kan order skenario Disconnect Order',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,18)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,18)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Menyelesaikan semua skenario test SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,18)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,18)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Mereview attribute product mencatat yang kurang atau ada yang ingin diubah',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,21)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,21)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat order test baru untuk Akses Jasa Call Center',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,21)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,21)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'UAT FAB IT Tools Layanan Akses Call Center',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,22)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,22)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat test order skenario AO 1 sampai 5 skenario Akses Jasa Call Center',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,22)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,22)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat order skenario SO Akses Jasa Call Center',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,22)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,22)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Membuat order skenario MO Akses Jasa Call Center',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,22)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,22)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => 'Tes 8IC IT Tools end to end SCC 3.0',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,23)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,23)->toDateTimeString(),
                'status' => 'Completed',
            ],
            [
                'name' => '',
                'start_date' => \Carbon\Carbon::createFromDate(2023,8,1)->toDateTimeString(),
                'end_date' => \Carbon\Carbon::createFromDate(2023,8,1)->toDateTimeString(),
                'status' => 'Completed',
            ],
            
        ];
        
        foreach ($activities as $activity) 
        {
            $activity['user_id'] = 1;
            activity::create($activity);
        }
    }
}
